### ISSUE TITLE
Request: don't require `text` if there are `attachments` passed to `slack_message()`

### ISSUE THREAD

**Issue by njncalub** [lamby/django-slack#16]
Using version 4.1.0, `slack_message()` is checking if the `data['text']` is blank. I was hoping we could just send a formatted text attachment with no `text`.

**Comment by lamby** [comment]
It's a required field by the upstream API:

![](http://i.imgur.com/jxYBk8E.png)

(via https://api.slack.com/methods/chat.postMessage)

If you can come up with a reliable workaround (sending a space, etc.) I would be happy to incorporate it, otherwise there's little `django-slack` can really do, alas.
